(()=>{
const cfg=window.ZD_CONFIG,$=s=>document.querySelector(s),TOKEN_KEY='zd_github_token_v1',state={latest:null,busy:false};
const ui={dot:$('#statusDot'),status:$('#statusText'),badge:$('#slotBadge'),updated:$('#updatedAt'),title:$('#contentTitle'),hook:$('#contentHook'),duration:$('#durationBadge'),voice:$('#voiceBadge'),box:$('#previewBox'),video:$('#video'),preview:$('#previewBtn'),share:$('#shareBtn'),skip:$('#skipBtn'),create:$('#createBtn'),message:$('#message')};
function msg(t=''){ui.message.textContent=t}
function online(v){ui.dot.classList.toggle('online',v);ui.dot.classList.toggle('error',!v)}
function fmtDate(v){if(!v)return'';try{return new Date(v).toLocaleString('tr-TR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}catch{return''}}
function decisionClass(d){return d==='approved'?'approved':d==='rejected'?'rejected':''}
function applyButtons(d={}){const ready=!!(d.video||cfg.defaultVideo);ui.preview.disabled=!ready;ui.share.disabled=!ready||d.decision==='approved'||state.busy;ui.skip.disabled=!ready||d.decision==='rejected'||state.busy;ui.create.disabled=state.busy}
function setBusy(v){state.busy=!!v;applyButtons(state.latest||{});ui.create.classList.toggle('busy',state.busy)}
function render(d){state.latest=d;ui.title.textContent=d.title||'ZihinDakika';ui.hook.textContent=d.hook||'Video hazır. Önizleyip karar verebilirsin.';ui.status.textContent=d.status||'Video hazır • karar bekliyor';ui.updated.textContent=fmtDate(d.updated_at||d.generated_at);ui.duration.textContent=d.duration_seconds?`${Math.round(d.duration_seconds)} sn`:'— sn';ui.voice.textContent=d.voice_engine||'Türkçe AI ses';ui.badge.className=`badge ${decisionClass(d.decision)}`.trim();ui.badge.textContent=d.decision==='approved'?'ONAYLANDI':d.decision==='rejected'?'PAYLAŞILMADI':d.slot==='17:30'||d.slot==='20:30'?`${d.slot} İÇERİĞİ`:'EKSTRA İÇERİK';const src=d.video||cfg.defaultVideo;if(src){const ver=encodeURIComponent(d.generated_at||Date.now());const full=src+(src.includes('?')?'&':'?')+'v='+ver;if(ui.video.dataset.src!==full){ui.video.dataset.src=full;ui.video.src=full;ui.video.load()}ui.video.hidden=false}else ui.video.hidden=true;applyButtons(d);online(true)}
async function load(show=true){try{const r=await fetch(`${cfg.dataUrl}?v=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw Error(`HTTP ${r.status}`);render(await r.json());return true}catch(e){online(false);if(show){ui.status.textContent='Bulut verisine ulaşılamadı.';msg('Bağlantıyı kontrol edip tekrar dene.')}return false}}
async function preview(){if(!state.latest)await load();if(!ui.video.src){msg('Video henüz hazır değil.');return}ui.box.classList.remove('hidden');try{await ui.video.play();ui.box.scrollIntoView({behavior:'smooth',block:'center'});msg('')}catch{msg('Oynatmak için videonun üzerine dokun.')}}
function getToken(){let token=(localStorage.getItem(TOKEN_KEY)||'').trim();if(token)return token;token=(prompt("İlk kullanım için GitHub erişim anahtarını yapıştır. Anahtar yalnızca bu iPhone'da saklanır ve ZihinDakika deposunda Issues yazma yetkisi yeterlidir.")||'').trim();if(!token){msg('İlk bağlantı tamamlanmadan komut gönderilemez.');return''}localStorage.setItem(TOKEN_KEY,token);return token}
async function postCommand(type){const d=state.latest||{};if(type!=='CREATE_EXTRA'&&!d.id){msg('İçerik kimliği yüklenemedi. Sayfayı yenile.');return}const token=getToken();if(!token)return;const suffix=type==='CREATE_EXTRA'?'':`:${d.id}`;const title=`ZD_COMMAND: ${type}${suffix}`;const body=`ZihinDakika V3.1.1 mobil komutu: ${type}\n\nİçerik: ${d.title||'yeni içerik'}\nSürüm: ${cfg.version}`;setBusy(true);msg(type==='CREATE_EXTRA'?'Yeni içerik üretimi başlatılıyor…':'Kararın gönderiliyor…');try{const r=await fetch(`https://api.github.com/repos/${cfg.repo}/issues`,{method:'POST',headers:{'Accept':'application/vnd.github+json','Authorization':`Bearer ${token}`,'X-GitHub-Api-Version':'2022-11-28','Content-Type':'application/json'},body:JSON.stringify({title,body})});if(!r.ok){const err=await r.json().catch(()=>({}));if(r.status===401||r.status===403)localStorage.removeItem(TOKEN_KEY);throw Error(err.message||`GitHub HTTP ${r.status}`)}if(type==='CREATE_EXTRA'){const oldId=d.id||'';msg('Üretim başladı. Video hazırlanıyor…');await waitForNewContent(oldId)}else{msg(type==='APPROVE'?'Paylaşım onayı gönderildi.':'İçerik paylaşılmayacak.');await waitForDecision(type)}}catch(e){setBusy(false);msg(`Komut gönderilemedi: ${e.message}. ${/401|403|credentials|Bad credentials/i.test(e.message)?'GitHub anahtarını yeniden gir.':''}`.trim())}}
async function waitForNewContent(oldId){for(let i=0;i<36;i++){await new Promise(r=>setTimeout(r,10000));const ok=await load(false);if(ok&&state.latest&&state.latest.id&&state.latest.id!==oldId){setBusy(false);msg('Yeni içerik hazır. Önizleyebilirsin.');return}}setBusy(false);msg('Üretim beklenenden uzun sürüyor. Sayfayı açık bırakabilirsin; hazır olduğunda otomatik yenilenecek.')}
async function waitForDecision(type){const wanted=type==='APPROVE'?'approved':'rejected';for(let i=0;i<18;i++){await new Promise(r=>setTimeout(r,5000));const ok=await load(false);if(ok&&state.latest&&state.latest.decision===wanted){setBusy(false);msg(wanted==='approved'?'Onay kaydedildi.':'Paylaşmama kararı kaydedildi.');return}}setBusy(false)}
ui.preview.addEventListener('click',preview);ui.share.addEventListener('click',()=>postCommand('APPROVE'));ui.skip.addEventListener('click',()=>postCommand('REJECT'));ui.create.addEventListener('click',()=>postCommand('CREATE_EXTRA'));ui.video.addEventListener('error',()=>msg('Video dosyası açılamadı. Yeni içerik üretmeyi deneyebilirsin.'));document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')load(false)});load();setInterval(()=>load(false),60000);if('serviceWorker'in navigator){navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'}).then(r=>r.update()).catch(()=>{})}
})();
