name: ZihinDakika-Core-Installer

on:
  push:
    paths:
      - .github/workflows/install-core.yml
      - zihindakika-install.zip
  workflow_dispatch:

permissions:
  contents: write

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install core
        run: |
          test -f zihindakika-install.zip || exit 0
          unzip -o zihindakika-install.zip
          rm -f .github/workflows/commands.yml
          rm -f .github/workflows/generate.yml
          rm -f .github/workflows/zihindakika.yml
          rm -f zihindakika-install.zip

          git config user.name ZihinDakika-Bot
          git config user.email actions@users.noreply.github.com
          git add .
          git diff --cached --quiet && exit 0
          git commit -m Install-ZihinDakika-Core
          git push
